<?php

namespace AppBundle\Repository;

/**
 * ParserHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
